spring.application.name=TaskFlow

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5433/taskflow
spring.datasource.username=postgres
spring.datasource.password=20050417
spring.datasource.driver-class-name=org.postgresql.Driver
